title: wklchris 的博客 - wklchris' blog
author: wklchris
email: wklchris AT hotmail DOT com
description: > # this means to ignore newlines until "baseurl:"
  This is wklchris' blog. Please refer to the original page if repost. 
  这里是 wklchris 的博客。如有转载，请注明出处页面。
baseurl: ""
github_username:  wklchris
duoshuo: true

defaults:
  -
    scope:
      path: "posts" # 一个空的字符串代表项目中所有的文件
    values:
      layout: "default"
      theme: minima
      permalink: date


# Build settings
markdown: kramdown
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock

disqus:
  shortname: wklchris