title: qiaoxi' notes
author: qiaoxi
email: gogolqx AT gmail DOT com
description: > # this means to ignore newlines until "baseurl:"
  This is qiaoxi's notes. Please refer to the original page if repost. 
  
baseurl: ""
github_username:  gogolqx
#  username: SirDong
#  urlid: wklchris
#google_analytics: UA-90643174-1

defaults:
  -
    scope:
      path: "posts" # 一个空的字符串代表项目中所有的文件
    values:
      layout: "default"
      theme: minima


# Build settings
permalink: /:title.html
excerpt_separator: "<!-- more -->"
markdown: kramdown

kramdown:
  toc_levels: 1..3  # 默认目录级别 h1-h3
  input: GFM
  syntax_highlighter: rouge
  
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock
  - ipynb/

disqus:
  shortname: qiaoxi